"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import { Ambulance, Award, Building2, Clock, CreditCard, Mail, MapPin, Navigation, Phone, Shield, Star, Stethoscope, Users } from "lucide-react";
import api, { IMAGE_BASE_URL } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

export default function HospitalProfilePage() {
  const { id } = useParams();
  const [hospital, setHospital] = useState(null);
  const [reviews, setReviews] = useState([]);
  const [reviewMeta, setReviewMeta] = useState({ currentPage: 1, totalPages: 1, totalItems: 0 });
  const [reviewPage, setReviewPage] = useState(1); const [ratingFilter, setRatingFilter] = useState("all");
  const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const [form, setForm] = useState({ patientName: "", rating: "5", title: "", comment: "", treatmentType: "" });

  useEffect(() => { setLoading(true); api.get(`/hospital/${id}`).then(({ data }) => setHospital(data)).catch(() => setError("হাসপাতালের তথ্য পাওয়া যায়নি")).finally(() => setLoading(false)); }, [id]);
  useEffect(() => { api.get(`/hospital/${id}/reviews`, { params: { page: reviewPage, limit: 6, rating: ratingFilter === "all" ? undefined : ratingFilter } }).then(({ data }) => { setReviews(data.data); setReviewMeta(data.pagination); }).catch(() => { setReviews([]); }); }, [id, reviewPage, ratingFilter]);

  const submitReview = async (event) => { event.preventDefault(); setMessage(""); try { const submitted={ ...form, rating:Number(form.rating) }; await api.post(`/hospital/${id}/reviews`, submitted); setMessage(`আপনার রিভিউ জমা হয়েছে এবং অনুমোদনের অপেক্ষায় আছে — ${submitted.patientName}: ${submitted.comment}`); setForm({ patientName: "", rating: "5", title: "", comment: "", treatmentType: "" }); } catch (err) { setMessage(err.response?.data?.message || "রিভিউ পাঠানো যায়নি"); } };

  if (loading) return <main className="min-h-[70vh] p-12 text-center text-sky-800">হাসপাতাল লোড হচ্ছে...</main>;
  if (error || !hospital) return <main className="min-h-[70vh] p-12 text-center text-red-700">{error}</main>;
  const info = hospital.basicInfo || {}; const contact = hospital.contact || {}; const address = hospital.address || {};
  const fullAddress = [address.street, address.city, address.state, address.postalCode, address.country].filter(Boolean).join(", ");
  const doctors = [...new Map((hospital.departments || []).flatMap((department) => department.doctors || []).filter(Boolean).map((doctor) => [doctor._id, doctor])).values()];

  return <main className="min-h-screen bg-gradient-to-br from-sky-50 to-blue-50">
    <section className="border-b bg-white"><div className="mx-auto max-w-7xl px-4 py-4 text-sm"><Link href="/hospitals" className="text-sky-700">হাসপাতাল</Link> <span className="mx-2">/</span> {info.name}</div></section>
    {info.images?.[0] && <div className="h-56 w-full bg-cover bg-center md:h-80" style={{ backgroundImage: `linear-gradient(rgba(0,0,0,.25),rgba(0,0,0,.25)),url(${IMAGE_BASE_URL}${info.images[0]})` }} />}
    <section className="mx-auto max-w-7xl space-y-8 px-4 py-8">
      <Card><CardContent className="grid gap-6 p-6 md:grid-cols-[auto_1fr_auto]"><Avatar className="h-24 w-24"><AvatarImage src={info.logo ? `${IMAGE_BASE_URL}${info.logo}` : ""} /><AvatarFallback><Building2 className="h-10 w-10" /></AvatarFallback></Avatar><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-3xl font-bold text-sky-900">{info.name}</h1><Badge variant="outline">{info.type}</Badge>{info.is24Hours && <Badge className="bg-green-100 text-green-800">২৪ ঘণ্টা খোলা</Badge>}</div><p className="mt-3 flex items-center gap-2 text-sky-700"><MapPin className="h-4 w-4" />{fullAddress || "ঠিকানা যোগ করা হয়নি"}</p><p className="mt-2 flex items-center gap-2"><Star className="h-4 w-4 fill-amber-400 text-amber-400" />{info.ratingAverage || 0} · {info.reviewCount || 0} রিভিউ</p><div className="mt-3 flex flex-wrap gap-4 text-sm"><span className="flex gap-1"><Users className="h-4 w-4" />{info.bedCount || 0} শয্যা</span>{info.establishedYear && <span className="flex gap-1"><Clock className="h-4 w-4" />প্রতিষ্ঠিত {info.establishedYear}</span>}</div></div><div className="flex flex-col gap-2">{contact.phone && <Button onClick={() => window.location.href = `tel:${contact.phone}`}><Phone className="mr-2 h-4 w-4" />কল করুন</Button>}{info.emergencyPhone && <Button variant="destructive" onClick={() => window.location.href = `tel:${info.emergencyPhone}`}>জরুরি কল</Button>}{contact.email && <Button asChild variant="outline"><a href={`mailto:${contact.email}`}><Mail className="mr-2 h-4 w-4" />ইমেইল</a></Button>}{fullAddress && <Button asChild variant="outline"><a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(fullAddress)}`} target="_blank" rel="noreferrer"><Navigation className="mr-2 h-4 w-4" />দিকনির্দেশ</a></Button>}{contact.website && <Button asChild variant="outline"><a href={contact.website} target="_blank" rel="noreferrer">ওয়েবসাইট</a></Button>}</div></CardContent></Card>

      <div className="grid gap-8 lg:grid-cols-3"><div className="space-y-8 lg:col-span-2">
        {info.description && <Card><CardHeader><CardTitle>হাসপাতাল সম্পর্কে</CardTitle></CardHeader><CardContent className="whitespace-pre-line leading-7">{info.description}</CardContent></Card>}
        {(hospital.departments || []).length > 0 && <Card><CardHeader><CardTitle>বিভাগসমূহ</CardTitle></CardHeader><CardContent className="grid gap-4 md:grid-cols-2">{hospital.departments.map((department) => <div key={department._id} className="rounded-lg border p-4"><h3 className="font-semibold text-sky-900">{department.name}</h3>{department.services?.length > 0 && <div className="mt-3 flex flex-wrap gap-2">{department.services.map((service) => <Badge key={service} variant="secondary">{service}</Badge>)}</div>}<p className="mt-3 text-sm text-muted-foreground">{department.doctors?.length || 0} জন ডাক্তার</p></div>)}</CardContent></Card>}
        {doctors.length > 0 && <Card><CardHeader><CardTitle>সংযুক্ত ডাক্তার ({doctors.length})</CardTitle></CardHeader><CardContent className="grid gap-4 md:grid-cols-2">{doctors.map((doctor) => <div key={doctor._id} className="rounded-lg border p-4"><Link href={`/doctor/${doctor.slug || doctor._id}`} className="flex gap-3 hover:text-sky-700"><Avatar><AvatarImage src={doctor.personalDetails?.profilePicture ? `${IMAGE_BASE_URL}${doctor.personalDetails.profilePicture}` : ""} /><AvatarFallback><Stethoscope /></AvatarFallback></Avatar><div><p className="font-semibold">ডা. {doctor.personalDetails?.firstName} {doctor.personalDetails?.lastName}</p><p className="text-sm text-muted-foreground">{doctor.professional?.field || doctor.specialization?.[0]?.field}</p><p className="mt-1 flex items-center gap-1 text-xs text-amber-600"><Star className="h-3 w-3 fill-current" />{doctor.ratingAverage || 0} ({doctor.reviewCount || 0})</p></div></Link><div className="mt-3 flex gap-2"><Button asChild size="sm" variant="outline" className="flex-1"><Link href={`/doctor/${doctor.slug || doctor._id}`}>প্রোফাইল</Link></Button><Button asChild size="sm" className="flex-1"><Link href={`/appointment?doctorId=${doctor._id}`}>অ্যাপয়েন্টমেন্ট</Link></Button></div></div>)}</CardContent></Card>}
        <Card><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><CardTitle>রোগীদের মতামত ({reviewMeta.totalItems})</CardTitle><Select value={ratingFilter} onValueChange={(value) => { setRatingFilter(value); setReviewPage(1); }}><SelectTrigger className="w-36"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">সব রেটিং</SelectItem>{[5,4,3,2,1].map((rating) => <SelectItem key={rating} value={String(rating)}>{rating} তারকা</SelectItem>)}</SelectContent></Select></div></CardHeader><CardContent className="space-y-4">{reviews.length === 0 ? <p className="text-muted-foreground">এখনও কোনো অনুমোদিত রিভিউ নেই।</p> : reviews.map((review) => <div key={review._id} className="rounded-lg border p-4"><div className="flex justify-between gap-3"><b>{review.patientName}</b><span className="flex">{[1,2,3,4,5].map((value) => <Star key={value} className={`h-4 w-4 ${value <= review.rating ? "fill-amber-400 text-amber-400" : "text-gray-300"}`} />)}</span></div>{review.title && <p className="mt-2 font-medium">{review.title}</p>}<p className="mt-2 text-sm leading-6">{review.comment}</p></div>)}{reviewMeta.totalPages > 1 && <div className="flex justify-center gap-3"><Button variant="outline" disabled={reviewPage <= 1} onClick={() => setReviewPage((page) => page - 1)}>আগের</Button><Button variant="outline" disabled={reviewPage >= reviewMeta.totalPages} onClick={() => setReviewPage((page) => page + 1)}>পরের</Button></div>}</CardContent></Card>
        <Card><CardHeader><CardTitle>রিভিউ দিন</CardTitle></CardHeader><CardContent><form onSubmit={submitReview} className="space-y-4">{message && <p className="rounded-md bg-sky-50 p-3 text-sky-800">{message}</p>}<div className="grid gap-4 md:grid-cols-2"><div><Label>আপনার নাম</Label><Input required value={form.patientName} onChange={(e) => setForm({ ...form, patientName: e.target.value })} /></div><div><Label>রেটিং</Label><Select value={form.rating} onValueChange={(value) => setForm({ ...form, rating: value })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{[5,4,3,2,1].map((value) => <SelectItem key={value} value={String(value)}>{value} তারকা</SelectItem>)}</SelectContent></Select></div></div><div><Label>শিরোনাম</Label><Input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></div><div><Label>চিকিৎসার ধরন</Label><Input value={form.treatmentType} onChange={(e) => setForm({ ...form, treatmentType: e.target.value })} /></div><div><Label>মতামত</Label><Textarea required minLength={10} value={form.comment} onChange={(e) => setForm({ ...form, comment: e.target.value })} /></div><Button>রিভিউ পাঠান</Button></form></CardContent></Card>
      </div><aside className="space-y-6">
        {info.services?.length > 0 && <Card><CardHeader><CardTitle>সেবাসমূহ</CardTitle></CardHeader><CardContent className="flex flex-wrap gap-2">{info.services.map((service) => <Badge key={service} variant="secondary">{service}</Badge>)}</CardContent></Card>}
        {info.facilities?.length > 0 && <Card><CardHeader><CardTitle>সুবিধাসমূহ</CardTitle></CardHeader><CardContent className="space-y-2">{info.facilities.map((facility) => <p key={facility} className="flex gap-2"><Shield className="h-4 w-4 text-green-600" />{facility}</p>)}</CardContent></Card>}
        {info.visitingHours?.length > 0 && <Card><CardHeader><CardTitle>ভিজিটিং আওয়ার</CardTitle></CardHeader><CardContent className="space-y-2 text-sm">{info.visitingHours.map((slot) => <div key={`${slot.day}-${slot.open}`} className="flex justify-between gap-3"><span>{slot.day}</span><span>{slot.open}–{slot.close}</span></div>)}</CardContent></Card>}
        {info.insurance?.length > 0 && <Card><CardHeader><CardTitle className="flex gap-2"><CreditCard />গৃহীত বীমা</CardTitle></CardHeader><CardContent className="flex flex-wrap gap-2">{info.insurance.map((item) => <Badge key={item} variant="outline">{item}</Badge>)}</CardContent></Card>}
        {info.accreditations?.length > 0 && <Card><CardHeader><CardTitle className="flex gap-2"><Award />স্বীকৃতি</CardTitle></CardHeader><CardContent className="space-y-2">{info.accreditations.map((item) => <p key={item}>{item}</p>)}</CardContent></Card>}
        <Card><CardHeader><CardTitle>জরুরি যোগাযোগ</CardTitle></CardHeader><CardContent className="space-y-2">{info.emergencyPhone && <Button className="w-full" variant="destructive" onClick={() => window.location.href = `tel:${info.emergencyPhone}`}><Phone className="mr-2 h-4 w-4" />{info.emergencyPhone}</Button>}{info.ambulancePhone && <Button className="w-full" variant="outline" onClick={() => window.location.href = `tel:${info.ambulancePhone}`}><Ambulance className="mr-2 h-4 w-4" />{info.ambulancePhone}</Button>}</CardContent></Card>
      </aside></div>
    </section>
  </main>;
}
