"use client";
import {useEffect,useState} from 'react';
import api from '@/lib/api';
const input='w-full rounded border bg-white p-2';
const days=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
export default function DoctorProfileEditor({scheduleOnly=false}){
  const [form,setForm]=useState(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  async function load(){try{const{data}=await api.get('/portal/profile');const d=data.data;setForm({phone:d.personalDetails?.phone||'',about:d.personalDetails?.about||'',consultationFee:d.professional?.consultationFee||0,chambers:d.chambers||[]});setMessage('');}catch(e){setMessage(e.response?.data?.message||'Profile could not load');}}
  useEffect(()=>{load();},[]);
  const change=(i,key,value)=>setForm(f=>({...f,chambers:f.chambers.map((c,n)=>i===n?{...c,[key]:value}:c)}));
  if(!form)return <div role="status">{message||'Loading profile…'}<button className="ml-3 underline" onClick={load}>Retry</button></div>;
  return <form className="space-y-5 rounded-xl border bg-white p-5" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await api.patch('/portal/profile',form);setMessage('Saved. The public profile now uses these details.');}catch(e){setMessage(e.response?.data?.message||'Save failed');}finally{setBusy(false);}}}><h2 className="text-xl font-bold">{scheduleOnly?'Chambers & hours':'Doctor profile'}</h2><p className="text-sm">Identity, account linkage and publication status are managed by an administrator. Schedule changes apply to new bookings; existing appointments are not moved automatically.</p>
  {!scheduleOnly&&<><label className="block">Phone *<input className={input} required type="tel" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label className="block">About<textarea className={input} value={form.about} onChange={e=>setForm({...form,about:e.target.value})}/></label><label className="block">Consultation fee (BDT) *<input className={input} required type="number" min="0" value={form.consultationFee} onChange={e=>setForm({...form,consultationFee:Number(e.target.value)})}/></label></>}
  <h3 className="font-semibold">Chamber schedules</h3>{form.chambers.map((c,i)=><fieldset key={c._id||i} className="grid gap-3 rounded border p-3 sm:grid-cols-2"><legend>Chamber {i+1}</legend><label>Name *<input className={input} required value={c.chamberName} onChange={e=>change(i,'chamberName',e.target.value)}/></label><label>Day *<select className={input} value={c.day} onChange={e=>change(i,'day',e.target.value)}>{days.map(d=><option key={d}>{d}</option>)}</select></label><label>From *<input className={input} required type="time" value={c.from} onChange={e=>change(i,'from',e.target.value)}/></label><label>To *<input className={input} required type="time" value={c.to} onChange={e=>change(i,'to',e.target.value)}/></label><label>Contact<input className={input} value={c.contactNumber||''} onChange={e=>change(i,'contactNumber',e.target.value)}/></label><label>District<input className={input} value={c.address?.state||''} onChange={e=>change(i,'address',{...c.address,state:e.target.value})}/></label><label>City<input className={input} value={c.address?.city||''} onChange={e=>change(i,'address',{...c.address,city:e.target.value})}/></label><button type="button" className="rounded border p-2 text-red-700" onClick={()=>setForm(f=>({...f,chambers:f.chambers.filter((_,n)=>n!==i)}))}>Remove this schedule</button></fieldset>)}<button type="button" className="rounded border px-4 py-2" onClick={()=>setForm(f=>({...f,chambers:[...f.chambers,{day:'Monday',from:'09:00',to:'17:00',chamberName:'',address:{}}]}))}>Add schedule</button><button className="ml-3 rounded bg-sky-700 px-4 py-2 text-white disabled:opacity-50" disabled={busy}>Save profile</button>{message&&<p role="status">{message}</p>}</form>;
}
