"use client";
import {useCallback,useEffect,useState,useRef} from 'react';
import Link from 'next/link';
import api from '@/lib/api';
import {formatTime} from '@/lib/doctor-display';

const button='min-h-11 rounded-md border bg-white px-4 py-2 text-sm hover:bg-sky-50 disabled:opacity-50';
const input='w-full rounded-md border bg-white p-2';
const card='space-y-3 rounded-xl border bg-white p-5';
function useData(endpoint,page=1){
  const [data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[tick,setTick]=useState(0);
  const key=useRef('');
  const refresh=useCallback(()=>setTick(x=>x+1),[]);
  useEffect(()=>{let active=true;const nextKey=`${endpoint}:${page}`;if(key.current!==nextKey){key.current=nextKey;setData(null);setError('');setLoading(true);}if(!endpoint){setLoading(false);return;}api.get(endpoint,{params:{page,limit:10}}).then(r=>{if(active){setData(r.data);setError('');}}).catch(e=>{if(active)setError(e.response?.data?.message||'Could not load records. Please retry.');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[endpoint,page,tick]);
  useEffect(()=>{const id=setInterval(refresh,20000);return()=>clearInterval(id);},[refresh]);
  return{data,error,loading,refresh};
}
function Pages({data,page,setPage}){return <div className="mt-4 flex flex-wrap items-center justify-center gap-3"><button className={button} disabled={page<=1} onClick={()=>setPage(x=>x-1)}>Previous</button><span>Page {page} / {Math.max(data?.pagination?.totalPages||1,1)}</span><button className={button} disabled={page>=Math.max(data?.pagination?.totalPages||1,1)} onClick={()=>setPage(x=>x+1)}>Next</button></div>;}
function Status({source}){return <>{source.loading&&<p role="status">Loading…</p>}{source.error&&<p role="alert" className="rounded border border-red-200 bg-red-50 p-3">{source.error} <button className="underline" onClick={source.refresh}>Retry</button></p>}</>;}
const nameOf=d=>[d?.personalDetails?.firstName,d?.personalDetails?.middleName,d?.personalDetails?.lastName].filter(Boolean).join(' ');

export default function PortalWorkspace({mode,doctor=false}){
  const [page,setPage]=useState(1),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
  const endpoint=mode==='overview'||mode==='analytics'?'/portal/stats':mode==='reviews'?'/portal/reviews':mode==='prescriptions'?'/portal/prescriptions':mode==='reminders'?'/portal/reminders':mode==='favorites'?'/users/favorites/doctors':mode==='messages'?null:'/portal/appointments'+(mode==='history'?'?status=completed':'');
  const source=useData(endpoint,page); const items=source.data?.data||[];
  async function action(fn){setBusy(true);setNotice('');try{await fn();source.refresh();setNotice('Saved successfully.');}catch(e){setNotice(e.response?.data?.message||'Action failed. Please retry.');}finally{setBusy(false);}}
  if(mode==='messages')return <Messages/>;
  return <div className="space-y-4"><h2 className="text-xl font-bold capitalize">{mode==='patients'?'Patient encounters':mode}</h2><Status source={source}/>{notice&&<p role="status" className="rounded border bg-white p-3">{notice}</p>}
    {['overview','analytics'].includes(mode)&&source.data&&<><div className="grid gap-3 sm:grid-cols-2">{[['Appointments','total'],['Pending / confirmed','upcoming'],['Completed visits','completed'],['Recorded paid fees (BDT)','recordedPaidFees']].map(([label,key])=><div className={card} key={key}><p>{label}</p><strong className="text-2xl">{source.data.data[key]}</strong></div>)}</div><p className="text-sm">Figures reflect saved appointment records, not a payment gateway or bank balance.</p><Link className="underline" href={`/dashboard/${doctor?'doctor':'patient'}/appointments`}>Manage appointments</Link></>}
    {mode==='prescriptions'&&doctor&&<PrescriptionForm onSaved={source.refresh}/>}
    {mode==='reminders'&&<ReminderForm onSaved={source.refresh}/>}
    {!['overview','analytics'].includes(mode)&&!source.loading&&Array.isArray(items)&&items.length===0&&<p className={card}>No records found.</p>}
    {Array.isArray(items)&&items.map(item=><article className={card} key={item._id||item.id}>
      {['appointments','patients','history'].includes(mode)&&<><h3 className="font-bold">{item.appointmentNumber} · {doctor?item.patient?.name:nameOf(item.doctor)}</h3><p>{new Date(item.appointmentDate).toLocaleDateString()} · {formatTime(item.timeSlot)} · {item.status}</p>{doctor&&<><p>Phone: {item.patient?.phone}</p><p>Reason: {item.reason||'Not provided'}</p></>}{doctor&&mode==='appointments'&&<label className="block">Status<select aria-label={`Status ${item.appointmentNumber}`} className={input} disabled={busy} value={item.status} onChange={e=>{const status=e.target.value;action(()=>api.patch(`/portal/appointments/${item._id}`,{status}));}}>{['pending','confirmed','completed','cancelled','no-show'].map(s=><option key={s} disabled={s==='pending'}>{s}</option>)}</select></label>}{!doctor&&mode==='appointments'&&['pending','confirmed'].includes(item.status)&&<button className={button} disabled={busy} onClick={()=>action(()=>api.patch(`/appointments/${item._id}/cancel`))}>Cancel appointment</button>}</>}
      {mode==='reviews'&&<><h3 className="font-bold">{item.patientName} · {item.rating}/5</h3><p>{item.comment}</p><p className="text-sm">Approved patient feedback</p></>}
      {mode==='prescriptions'&&<><h3 className="font-bold">{item.appointment?.appointmentNumber} · {item.appointment?.patient?.name}</h3><p className="whitespace-pre-wrap">{item.instructions}</p><p>{new Date(item.createdAt).toLocaleString()}</p>{item.fileName&&<button className={button} disabled={busy} onClick={()=>action(async()=>{const r=await api.get(`/portal/prescriptions/${item._id}/file`,{responseType:'blob'});const url=URL.createObjectURL(r.data);const a=document.createElement('a');a.href=url;a.download=item.fileName;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);})}>Download {item.fileName}</button>}</>}
      {mode==='reminders'&&<><h3 className="font-bold">{item.title}</h3><p>{new Date(item.dueAt).toLocaleString()} · {item.completed?'Completed':new Date(item.dueAt)<=new Date()?'Due':'Upcoming'}</p><button className={button} disabled={busy} onClick={()=>action(()=>api.patch(`/portal/reminders/${item._id}`,{completed:!item.completed}))}>{item.completed?'Mark pending':'Mark completed'}</button></>}
      {mode==='favorites'&&<><Link href={`/doctor/${item.slug||item.id||item._id}`} className="font-bold underline">{nameOf(item)}</Link><button className={button} disabled={busy} onClick={()=>action(()=>api.post(`/users/favorites/doctors/${item.id||item._id}`))}>Remove from saved doctors</button></>}
    </article>)}
    {!['overview','analytics'].includes(mode)&&<Pages data={source.data} page={page} setPage={setPage}/>}
  </div>;
}
function AppointmentPicker({value,onChange}){const[page,setPage]=useState(1);const source=useData('/portal/appointments',page);return <div className="space-y-2"><Status source={source}/><label className="block">Appointment *<select className={input} required value={value} onChange={e=>onChange(e.target.value)}><option value="">Choose appointment from this page</option>{(source.data?.data||[]).map(x=><option key={x._id} value={x._id}>{x.appointmentNumber} · {x.patient?.name}</option>)}</select></label><Pages data={source.data} page={page} setPage={v=>{onChange('');setPage(v);}}/></div>;}
function PrescriptionForm({onSaved}){const[id,setId]=useState(''),[text,setText]=useState(''),[file,setFile]=useState(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);return <form className={card} onSubmit={async e=>{e.preventDefault();setBusy(true);try{const form=new FormData();form.append('appointmentId',id);form.append('instructions',text);if(file)form.append('file',file);await api.post('/portal/prescriptions',form);setText('');setFile(null);setId('');e.target.reset();setMessage('Prescription saved. The linked patient can view it in their account.');onSaved();}catch(e){setMessage(e.response?.data?.message||'Could not save prescription');}finally{setBusy(false);}}}><h3 className="font-bold">Record prescription</h3><AppointmentPicker value={id} onChange={setId}/><label className="block">Instructions<textarea className={input} maxLength={12000} value={text} onChange={e=>setText(e.target.value)}/></label><label className="block">Private attachment (PDF, PNG, JPEG; max 8 MB)<input type="file" accept="application/pdf,image/png,image/jpeg" onChange={e=>setFile(e.target.files[0]||null)}/></label><p className="text-sm">Guest appointments are visible only to the assigned doctor. Patient access requires a booking made from a patient account.</p><button className={button} disabled={busy||(!text.trim()&&!file)}>Save prescription</button>{message&&<p role="status">{message}</p>}</form>;}
function ReminderForm({onSaved}){const[title,setTitle]=useState(''),[dueAt,setDue]=useState(''),[message,setMessage]=useState('');return <form className={card} onSubmit={async e=>{e.preventDefault();try{await api.post('/portal/reminders',{title,dueAt:new Date(dueAt).toISOString()});setTitle('');setDue('');setMessage('Reminder saved.');onSaved();}catch(e){setMessage(e.response?.data?.message||'Save failed');}}}><p>In-app reminders only; no SMS, email or push notification is sent.</p><label className="block">Title *<input className={input} required maxLength={200} value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="block">Due date/time *<input className={input} required type="datetime-local" value={dueAt} onChange={e=>setDue(e.target.value)}/></label><button className={button}>Add reminder</button>{message&&<p role="status">{message}</p>}</form>;}
function Messages(){const[id,setId]=useState(''),[page,setPage]=useState(1),[text,setText]=useState(''),[message,setMessage]=useState('');const source=useData(id?`/portal/appointments/${id}/messages`:null,page);return <div className="space-y-4"><h2 className="text-xl font-bold">Appointment messages</h2><p>Not monitored for emergencies. Messages refresh every 20 seconds.</p><AppointmentPicker value={id} onChange={v=>{setId(v);setPage(1);}}/><Status source={source}/>{id&&<><form className={card} onSubmit={async e=>{e.preventDefault();try{await api.post(`/portal/appointments/${id}/messages`,{text});setText('');source.refresh();setMessage('Message sent.');}catch(e){setMessage(e.response?.data?.message||'Could not send message');}}}><label>Message *<textarea className={input} required maxLength={2000} value={text} onChange={e=>setText(e.target.value)}/></label><button className={button}>Send message</button>{message&&<p role="status">{message}</p>}</form>{(source.data?.data||[]).map(x=><div className={card} key={x._id}><strong>{x.senderRole} · {new Date(x.createdAt).toLocaleString()}</strong><p className="whitespace-pre-wrap">{x.text}</p></div>)}<Pages data={source.data} page={page} setPage={setPage}/></>}</div>;}
